package org.joy.swing.dialog;

import org.joy.commons.lang.string.I18nTool;
import org.joy.swing.SwingUtility;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * 批量设置的对话框
 * @author  zy
 */
public class BatchSettingDialog extends javax.swing.JDialog implements ActionListener {

    private static BatchSettingDialog batchSettingDialog = null;
    private CellEditor editor;

    /**
     * 操作结果
     */
    public static enum ACTION {

        /**
         * 点击确定
         */
        OK_ACTION,
        /**
         * 点击取消
         */
        CANCEL_ACTION
    }
    private ACTION action = ACTION.CANCEL_ACTION;

    /** Creates new form BatchSettingDialog */
    private BatchSettingDialog() {
        super(SwingUtility.getInstance().getMainFrame(), true);
        initComponents();
    }

    /**
     * 设置组件
     * @param cellEditor 单元格编辑器
     * @param component 编辑组件
     */
    public void setComponent(CellEditor cellEditor, Component component) {
        editor = cellEditor;
        componentPanel.removeAll();
        componentPanel.add(component);
        this.repaint();
    }

    /**
     * 取得编辑值
     * @return 返回编辑值
     */
    public Object getValue() {
        return editor.getCellEditorValue();
    }

    /**
     * 设置编辑属性的描述
     * @param name
     */
    public void setText(String name) {
        columnLabel.setText(name);
    }

    /**
     * 返回操作值
     * @return
     */
    public ACTION getAction() {
        return action;
    }

    /**
     * 显示对话框
     * @param cellEditor 单元格编辑器
     * @param component 编辑组件
     * @param settingName 名称
     * @return 返回对话框
     */
    public static BatchSettingDialog showDialog(CellEditor cellEditor, Component component, String settingName) {
        if (batchSettingDialog == null) {
            batchSettingDialog = new BatchSettingDialog();
        }
        batchSettingDialog.action = ACTION.CANCEL_ACTION;
        batchSettingDialog.setText(settingName);
        batchSettingDialog.setComponent(cellEditor, component);
        batchSettingDialog.setLocationRelativeTo(SwingUtility.getInstance().getMainFrame());
        batchSettingDialog.pack();
        batchSettingDialog.setVisible(true);

        return batchSettingDialog;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        componentPanel = new javax.swing.JPanel();
        columnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(I18nTool.getLocalStr("BatchRevision"));

        cancelButton.setText(I18nTool.getLocalStr("Cancel"));
        cancelButton.addActionListener(this);

        okButton.setText(I18nTool.getLocalStr("OK"));
        okButton.addActionListener(this);

        componentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(componentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(columnLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(columnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(componentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == cancelButton) {
            BatchSettingDialog.this.cancelButtonActionPerformed(evt);
        }
        else if (evt.getSource() == okButton) {
            BatchSettingDialog.this.okButtonActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

    if (editor.stopCellEditing()) {
        batchSettingDialog.action = ACTION.OK_ACTION;
        dispose();
    }
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

    batchSettingDialog.action = ACTION.CANCEL_ACTION;
    dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                BatchSettingDialog dialog = new BatchSettingDialog();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel columnLabel;
    private javax.swing.JPanel componentPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
