/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertyEditor.java
 *
 * Created on 2010-2-20, 14:45:53
 */

package com.kvc.joy.swing;

import com.kvc.joy.swing.button.XButton;

/**
 *
 * @author Kevice
 */
public class PropertyEditor extends javax.swing.JPanel {

    /** Creates new form PropertyEditor */
    public PropertyEditor() {
        initComponents();
    }

    public void setEditable(boolean editable) {
        formattedTextField.setEditable(editable);
    }

    public void setEnabled() {
        setEditable(false);
        button.setEnabled(false);
    }

    public XFormattedTextField getTextField() {
        return formattedTextField;
    }

    public XButton getButton() {
        return button;
    }

    public String getText() {
        return formattedTextField.getText();
    }

    public String getTrimText() {
        return getText().trim();
    }

    public void setText(String text) {
        formattedTextField.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new com.kvc.joy.swing.button.XButton();
        formattedTextField = new com.kvc.joy.swing.XFormattedTextField();

        setLayout(new java.awt.BorderLayout());

        button.setText("...");
        button.setPreferredSize(new java.awt.Dimension(21, 21));
        add(button, java.awt.BorderLayout.LINE_END);
        add(formattedTextField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kvc.joy.swing.button.XButton button;
    private com.kvc.joy.swing.XFormattedTextField formattedTextField;
    // End of variables declaration//GEN-END:variables

}
