/* 登陆失败原因代码 */
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGIN_STATE_00','1','1',null,null,null,null,null,null,'0',null,null,null,null,'00','登陆状态','login_state',null,null,'deng lu cheng gong',null,'登陆成功','login successfully');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGIN_STATE_11','1','1',null,null,null,null,null,null,'0',null,null,null,null,'11','登陆状态','login_state',null,null,'mi ma cuo wu',null,'密码错误','password error');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGIN_STATE_12','1','1',null,null,null,null,null,null,'0',null,null,null,null,'12','登陆状态','login_state',null,null,'yan zheng ma cuo wu',null,'验证码错误','verification code error');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGIN_STATE_21','1','1',null,null,null,null,null,null,'0',null,null,null,null,'21','登陆状态','login_state',null,null,'zhang hao suo ding',null,'帐号被锁定','account lock');

/* 登出系统方式代码 */
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGOUT_METHOD_11','1','1',null,null,null,null,null,null,'0',null,null,null,null,'11','登出系统方式','logout_method',null,null,'dian ji tui chu an niu',null,'点击退出按钮','click exit button');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGOUT_METHOD_12','1','1',null,null,null,null,null,null,'0',null,null,null,null,'12','登出系统方式','logout_method',null,null,'zhi jie guan bi liu lan qi',null,'直接关闭浏览器','close broswer directly');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGOUT_METHOD_21','1','1',null,null,null,null,null,null,'0',null,null,null,null,'21','登出系统方式','logout_method',null,null,'chao shi',null,'超时','timeout');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`description`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_CODE_LOGOUT_METHOD_99','1','1',null,null,null,null,null,null,'0',null,null,null,null,'99','登出系统方式','logout_method',null,null,'qi ta',null,'其它','other');

