/* 任务运行状态代码 */
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`remark`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_JOB_RUN_STATE_00','1','1',null,null,null,null,null,null,'0',null,null,null,null,'00','任务运行状态','job_run_state',null,null,'wei qi dong',null,'未启动','unstart');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`remark`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_JOB_RUN_STATE_11','1','1',null,null,null,null,null,null,'0',null,null,null,null,'11','任务运行状态','job_run_state',null,null,'yun xing zhong',null,'运行中','running');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`remark`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_JOB_RUN_STATE_21','1','1',null,null,null,null,null,null,'0',null,null,null,null,'21','任务运行状态','job_run_state',null,null,'yi chang zhong zhi',null,'异常终止','abnormal termination');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`remark`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_JOB_RUN_STATE_22','1','1',null,null,null,null,null,null,'0',null,null,null,null,'22','任务运行状态','job_run_state',null,null,'yong hu gua qi',null,'用户挂起','user pause');
insert into `t_sys_codes`(`id`,`active`,`built_in`,`create_dept`,`create_time`,`create_user`,`delete_dept`,`delete_time`,`delete_user`,`deleted`,`remark`,`update_dept`,`update_time`,`update_user`,`code`,`group_comment`,`group_id`,`ordinal`,`parent_code`,`pin_yin`,`segment_rule`,`trans`,`trnas_en_us`) 
values ('JOY_JOB_RUN_STATE_80','1','1',null,null,null,null,null,null,'0',null,null,null,null,'80','任务运行状态','job_run_state',null,null,'yi wan cheng',null,'已完成','finished');
