package com.kvc.joy.swing.datechooser;

import java.beans.PropertyChangeListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;

/**
 * 日期时间组件
 * @author ckcs
 */
public class DateTimeChooser extends javax.swing.JPanel {

    /** Creates new form DateTimeChooser */
    public DateTimeChooser() {
        initComponents();
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        fromDateChooser.setEnabled(enabled);
        fromTimeChooser.setEnabled(enabled);
    }

    public JSpinner getFromTimeChooser() {
        return fromTimeChooser;
    }

    /**
     * 初始日期时间选择器
     */
    public void initDateTimeChooser() {
        initDateTimeChooser(new Date(), new Date());
    }

    /**
     * 初始话日期时间选择器
     * @param fromDate
     * @param toDate
     */
    public void initDateTimeChooser(Date fromDate, Date toDate) {
        fromDateChooser.setDate(fromDate);
        if (fromDate == null) {
            fromTimeChooser.setValue(new Date(0));
        }
    }

    /**
     * 清空日期时间选择器
     */
    public void clearDateTimeChooser() {
        initDateTimeChooser(null, null);
    }

    /**
     * 获得起始得时间
     * @return
     */
    public Date getFromDateTime() {
        return getDateComp(fromDateChooser.getDate(), (Date) fromTimeChooser.getValue());
    }

    /**
     * 是否开始时间为null
     * @return
     */
    public boolean isFromDateTimeNull() {
        return (fromDateChooser.getDate() == null || fromTimeChooser.getValue() == null);
    }

    public void addFromDateChangeListener(PropertyChangeListener listner) {
        if (listner != null) {
            fromDateChooser.addPropertyChangeListener(listner);
        }
    }

    /**
     * 使用前个的日期, 后个的时间
     * @param useDate 使用日期
     * @param useTime 使用时间
     * @return
     */
    public Date getDateComp(Date useDate, Date useTime) {
        if (useDate == null || useTime == null) {
            return null;
        }
//日期部分
        Calendar first = Calendar.getInstance();
        first.setTime(useDate);
        //时间部分
        Calendar second = Calendar.getInstance();
        second.setTime(useTime);
        first.set(Calendar.HOUR_OF_DAY, second.get(Calendar.HOUR_OF_DAY));
        first.set(Calendar.MINUTE, second.get(Calendar.MINUTE));
        first.set(Calendar.SECOND, second.get(Calendar.SECOND));
        return first.getTime();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromDateChooser = new com.kvc.joy.swing.datechooser.XDateChooser();
        fromTimeChooser = new javax.swing.JSpinner();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fromDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addComponent(fromTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fromTimeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kvc.joy.swing.datechooser.XDateChooser fromDateChooser;
    private javax.swing.JSpinner fromTimeChooser;
    // End of variables declaration//GEN-END:variables
}
